spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gerd?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: gerd
    password: gerd
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
    open-in-view: false