-- Preserve existing meal record data while moving from the old single-table shape:
--
--   meal_records.id BIGINT IDENTITY
--   meal_records.meal_group_id UUID
--
-- to the current two-table shape:
--
--   meal_records.id UUID                  -- parent meal
--   meal_foods.meal_record_id UUID        -- child meal food record
--
-- The old table is kept as meal_records_legacy for recovery/debugging.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
DECLARE
    meal_record_id_type text;
BEGIN
    SELECT data_type
      INTO meal_record_id_type
      FROM information_schema.columns
     WHERE table_schema = current_schema()
       AND table_name = 'meal_records'
       AND column_name = 'id';

    IF meal_record_id_type IS NOT NULL
       AND meal_record_id_type <> 'uuid'
       AND to_regclass('meal_records_legacy') IS NULL THEN
        ALTER TABLE meal_records RENAME TO meal_records_legacy;
        ALTER INDEX IF EXISTS meal_records_pkey RENAME TO meal_records_legacy_pkey;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS meal_records (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL,
    eaten_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    modified_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS meal_foods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP(6),
    modified_at TIMESTAMP(6),
    user_id BIGINT NOT NULL,
    food_id BIGINT NOT NULL,
    meal_record_id UUID NOT NULL,
    eaten_at TIMESTAMP(6) NOT NULL,
    judged_grade VARCHAR(255),
    analysis_json TEXT,
    deleted_at TIMESTAMP(6)
);

DO $$
BEGIN
    IF to_regclass('meal_records_legacy') IS NOT NULL THEN
        EXECUTE '
            INSERT INTO meal_records (
                id,
                user_id,
                eaten_at,
                deleted_at,
                created_at,
                modified_at
            )
            SELECT
                legacy.meal_group_id,
                MIN(legacy.user_id),
                MIN(legacy.eaten_at),
                CASE
                    WHEN BOOL_AND(legacy.deleted_at IS NOT NULL) THEN MAX(legacy.deleted_at)
                    ELSE NULL
                END,
                MIN(legacy.created_at),
                MAX(legacy.modified_at)
            FROM meal_records_legacy legacy
            GROUP BY legacy.meal_group_id
            ON CONFLICT (id) DO NOTHING
        ';

        EXECUTE '
            INSERT INTO meal_foods (
                external_id,
                created_at,
                modified_at,
                user_id,
                food_id,
                meal_record_id,
                eaten_at,
                judged_grade,
                analysis_json,
                deleted_at
            )
            SELECT
                COALESCE(legacy.external_id, gen_random_uuid()),
                legacy.created_at,
                legacy.modified_at,
                legacy.user_id,
                legacy.food_id,
                legacy.meal_group_id,
                legacy.eaten_at,
                legacy.judged_grade,
                NULL,
                legacy.deleted_at
            FROM meal_records_legacy legacy
            ON CONFLICT (external_id) DO NOTHING
        ';
    END IF;
END $$;

DO $$
DECLARE
    symptom_meal_record_id_type text;
BEGIN
    SELECT data_type
      INTO symptom_meal_record_id_type
      FROM information_schema.columns
     WHERE table_schema = current_schema()
       AND table_name = 'symptom_records'
       AND column_name = 'meal_record_id';

    IF symptom_meal_record_id_type IS NOT NULL
       AND symptom_meal_record_id_type <> 'uuid'
       AND to_regclass('meal_records_legacy') IS NOT NULL THEN
        ALTER TABLE symptom_records ADD COLUMN IF NOT EXISTS meal_record_uuid UUID;

        UPDATE symptom_records symptom
           SET meal_record_uuid = legacy.meal_group_id
          FROM meal_records_legacy legacy
         WHERE symptom.meal_record_id = legacy.id;

        ALTER TABLE symptom_records DROP COLUMN meal_record_id;
        ALTER TABLE symptom_records RENAME COLUMN meal_record_uuid TO meal_record_id;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS meal_records_user_idx
    ON meal_records (user_id);

CREATE INDEX IF NOT EXISTS meal_foods_user_eaten_idx
    ON meal_foods (user_id, eaten_at);

CREATE INDEX IF NOT EXISTS meal_foods_record_idx
    ON meal_foods (meal_record_id);
